repos:
  # Ruff for linting and formatting
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.16.6  # Use the latest version
    hooks:
      # Run the linter (import sorting is included in Ruff's default rule set).
      - id: ruff-check
        args: [--fix]
        name: ruff-check
      # Run the formatter
      - id: ruff-format
        name: ruff-format

  # Pylint for additional static analysis
#  - repo: local
#    hooks:
#      - id: pylint
#        name: pylint
#        entry: uv run pylint
#        language: system
#        types: [python]
#        args:
#          [
#            db_batch
#          ]
